### ISSUE TITLE
Suggestion: make sure that all commits on the `main` branch compile

### ISSUE THREAD

**Issue by wetneb** [vigna/webgraph-rs#139]
Hello @vigna,

Thanks for maintaining webgraph! One suggestion I have is to make sure the `main` branch always has a green CI for all of its commits. It's [not quite the case yet](https://github.com/vigna/webgraph-rs/commits/main/) and is generally regarded as a good practice.

One way of achieving this is to squash PRs when merging them (assuming PRs indeed pass the CI when they are merged, of course, but I guess that should normally be the case). It's possible to configure the GitHub project so that this is the default merge method for PRs.
Another is to request PR authors to rearrange the commit log of their PRs so that the tests pass at each commit.

Here's some more info about my motivation: As part of some work on [swh-graph](https://gitlab.softwareheritage.org/swh/devel/swh-graph), I am trying to use the feature contributed by @progval at https://github.com/vigna/webgraph-rs/pull/138. Patching swh-graph to use this unreleased version of webgraph raises various compilation errors, and to fix them, I found it helpful to use `git bisect` on webgraph to identify commits which introduced a compilation error in swh-graph. Being able to see the commit in webgraph makes it easier for me to understand how to remediate the issue in swh-graph. However, using `git bisect` is difficult when the commit log contains various temporary build / test failures that are then fixed by a later commit, as this introduces noise.

Thanks again and looking forward to webgraph 0.4.0 :)

**Comment by progval** [comment]
even with a green CI, the `main` branch is going to be incompatible with swh-graph for various reasons (currently, incompatible versions of and epserde and sux are in flux). I'd recommend forking the repo from the release swh-graph uses and cherry-picking the PR in your own branch.

**Comment by progval** [comment]
btw, if you don't use it already, https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#using-patch-with-multiple-versions is very useful to replace transitive dependencies.

**Comment by vigna** [comment]
Yeah the last three months have been a little crazy because of parallel backward-incompatible motivations on all creates involved. That should end soon. I agree with you.

**Comment by wetneb** [comment]
> even with a green CI, the main branch is going to be incompatible with swh-graph for various reasons

That's clear. I don't expect that a green CI would forbid the introduction of any breaking change ;)

The point I was trying to make was that having a green CI at each commit would make it easier for me to upgrade swh-graph to work with the latest webgraph, by using `git bisect` to identify the commits that introduced the breakages.

> I'd recommend forking the repo from the release swh-graph uses and cherry-picking the PR in your own branch.

That sounds good, I couldn't tell if your feature was dependent on any recent changes in webgraph. So I'll try that.
